### ISSUE TITLE
inp file runs in SWMM GUI but with run_swmm "... EPA-SWMM completed in 0.00 seconds. There are errors."

### ISSUE THREAD

**Issue by gavanmcgrath** [dleutnant/swmmr#58] opened 2020-11-21 00:20 UTC
I have a SWMM model that runs fine in the GUI but when I call with run_swmm it ends abruptly with "... EPA-SWMM completed in 0.00 seconds. There are errors." . Any clues as to where I can start debugging this issue.

**Comment by gavanmcgrath** [comment] 2020-11-21 04:15
Follow up. When I set the working directory in R to the *.inp file location and scrub the file directory from the file names passed to  run_swmm it works.

**Comment by dleutnant** [comment] 2020-11-21 07:20
Please try the dev version from GitHub. You are probably using relative paths for external data.

**Comment by dleutnant** [comment] 2020-11-21 07:21
Also, the .rpt file contains debugging information.

**Comment by ichsan2895** [comment] 2020-11-28 16:53
> Please try the dev version from GitHub. You are probably using relative paths for external data.

I have face same issue. Here is my screenshot.
![image](https://user-images.githubusercontent.com/60387342/100521154-8dfe1980-31d4-11eb-810a-d2f324ae95e7.png)

My apps:
RStudio 1.3.959
R 3.6.3
SWMM 5.1.015 (I install it in `H:/SWMM/EPA SWMM 5.1.015/` instead of `C:/Program files`

**Comment by dleutnant** [comment] 2020-11-29 15:45
Could you copy the Example1.inp to a first level directory where you have full write access and run swmm again? E.g. in h:\Example1.inp ?

**Comment by dleutnant** [comment] 2020-11-30 14:06
@ichsan2895 I created a new issue from your comment as I assume the issue is not related to the one reported by @gavanmcgrath .

@gavanmcgrath Did you test the dev version? If so and your issues is solved, please consider to close this issue here. Thanks.

**Comment by gavanmcgrath** [comment] 2020-12-01 09:18
> @ichsan2895 I created a new issue from your comment as I assume the issue is not related to the one reported by @gavanmcgrath .
> 
> @gavanmcgrath Did you test the dev version? If so and your issue is solved, please consider to close this issue here. Thanks.

Issue is solved. Thanks for the suggestions.

**Closed** 2020-12-01 10:38 UTC
